title: "Cédric Paul MADJEKI-MA-MOUSSAVOU BIGNOUMBA"
logo: img/nny.jpg
description: "Portfolio Data, Statistique & Data Science,Ingénieur statisticien • Data Scientist • Chargé d'études statistiques • Chef de projet Data"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
